# File: Slots.RpOnly.yml
# Version: 2.0.0
# Change Log:
# - 1.0.0 (5/14/24): Initial template
# - 2.0.0 (7/3/24):
  # - Removing the  "DeployToStagePreview" parameter and "Deploy to MPAC RP" stage as it is already included in the RP Prod rollout.
  # - Removing BakeTime as the bake is included in the RP rolloutspec.
  # - Change name to Slots.RpOnly.yml from FriendlyName.RpOnly.yml
  # - Adding USNat and USSec support

# Deploys the Extension to MPAC, Production, MC and FF environments; RP Only
# This is a top-level YAML pipeline. It can be run directly.
# Using templates from https://onebranch.visualstudio.com/OneBranch.Pipelines/_git/GovernedTemplates?path=/v2/Steps/Release.Steps.yml&_a=contents&version=GBmaster
trigger: none # NOTE: Triggers are set on pipeline completion, under resources.pipelines below
parameters:
- name: SlotName
  displayName: SlotName - The slot name to be deployed.
  type: string
  default: ''
- name: SetOrRemoveSlotName
  displayName: Set or Remove the friendly name. (Only "Set" feature enabled right now )
  type: string
  default: Set
  values:
    - Set
    - Remove
- name: DeployToProd
  displayName: DeployToProd - Deploy to Prod
  type: boolean
  default: true
- name: DeployToFF
  displayName: DeployToFF - Deploy to Fairfax
  type: boolean
  default: true
- name: DeployToMC
  displayName: DeployToMC - Deploy to Mooncake
  type: boolean
  default: true
- name: DeployToUSNat
  displayName: DeployToUSNat - Deploy to USNat
  type: boolean
  default: true
- name: DeployToUSSec
  displayName: DeployToUSSec - Deploy to USSec
  type: boolean
  default: true
- name: BuildArtifactPattern
  displayName: BuildArtifactPattern - The pattern for the build artifact.
  type: string
  default: bin/Deployment
- name: ServiceRootPath
  displayName: ServiceRootPath - The root path for deployment files.
  type: string
  default: $(Pipeline.Workspace)/_OfficialBuild/drop_build_retail_amd64/$(BuildArtifactPattern)
resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main
  pipelines:
  # Reference https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines#properties for more information.
  # TO DO: Add Pipeline name
  - pipeline: # example: _OfficialBuild
  # TO DO: Add Pipeline source
    source: # example: AzureUX-PortalFx-Official
  # TO DO: Add Pipeline project
    project:  # example: One
extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    stages:
    # Set Pipeline Name
    - template: Common/Extension.common.SetPipelineName.yml
      parameters:
        DeployToStagePreview: true # true as it is included in the "Deploy to Prod RP" rollout
        DeployToProd: ${{ parameters.DeployToProd }}
        DeployToFF: ${{ parameters.DeployToFF }}
        DeployToMC: ${{ parameters.DeployToMC }}
        DeployToUSNat: ${{ parameters.DeployToUSNat }}
        DeployToUSSec: ${{ parameters.DeployToUSSec }}
        Action: 'DeployTo'
        ob_release_environment: 'Test'
    # Deploy to Prod RP
    - ${{ if parameters.DeployToProd }}:
      - template: Common/Extension.common.deploy.RP.yml
        parameters:
          SingleStageDependsOn: 'Test_set_pipeline_name'
          EnvironmentName: 'prod'
          EnvironmentType: Prod
          ob_release_environment: 'Production'
          BuildArtifactPattern: ${{ parameters.BuildArtifactPattern }}
          ServiceRootPath: ${{ parameters.ServiceRootPath }}
          RolloutSpecFileName: ${{ parameters.SlotName }}
          Action: 'Staging_${{ parameters.SlotName}}'
    # Deploy to FF RP
    - ${{ if parameters.DeployToFF }}:
      - template: Common/Extension.common.deploy.RP.yml
        parameters:
          ${{ if parameters.DeployToProd }}:
            SingleStageDependsOn:
              - 'Prod_RP_prod_Staging_${{ parameters.SlotName}}'
          ${{ else }}:
            SingleStageDependsOn: 'Test_set_pipeline_name'
          EnvironmentName: 'ff'
          EnvironmentType: FF
          ob_release_environment: 'Fairfax'
          BuildArtifactPattern: ${{ parameters.BuildArtifactPattern }}
          ServiceRootPath: ${{ parameters.ServiceRootPath }}
          RolloutSpecFileName: ${{ parameters.SlotName }}
          Action: 'Staging_${{ parameters.SlotName}}'
    # Deploy to MC RP
    - ${{ if parameters.DeployToMC }}:
      - template: Common/Extension.common.deploy.RP.yml
        parameters:
          ${{ if parameters.DeployToProd }}:
            SingleStageDependsOn:
              - 'Prod_RP_prod_Staging_${{ parameters.SlotName}}'
          ${{ else }}:
            SingleStageDependsOn: 'Test_set_pipeline_name'
          EnvironmentName: 'mc'
          EnvironmentType: MC
          ob_release_environment: 'Mooncake'
          BuildArtifactPattern: ${{ parameters.BuildArtifactPattern }}
          ServiceRootPath: ${{ parameters.ServiceRootPath }}
          RolloutSpecFileName: ${{ parameters.SlotName }}
          Action: 'Staging_${{ parameters.SlotName}}'
    # Deploy to USNat RP
    - ${{ if parameters.DeployToUSNat }}:
      - template: Common/Extension.common.deploy.RP.yml
        parameters:
          ${{ if parameters.DeployToMC }}:
            ${{ if parameters.DeployToFF }}:
              SingleStageDependsOn:
                - 'MC_RP_mc_Staging_${{ parameters.SlotName}}'
                - 'FF_RP_ff_Staging_${{ parameters.SlotName}}'
            ${{ else }}:
              SingleStageDependsOn:
                - 'MC_RP_mc_Staging_${{ parameters.SlotName}}'
          ${{ else }}:
            ${{ if parameters.DeployToFF }}:
              SingleStageDependsOn:
                - 'FF_RP_ff_Staging_${{ parameters.SlotName}}'
            ${{ else }}:
              ${{ if parameters.DeployToProd }}:
                SingleStageDependsOn:
                  - 'Prod_RP_prod_Staging_${{ parameters.SlotName}}'
              ${{ else }}:
                SingleStageDependsOn:
                  - 'Test_set_pipeline_name'
          EnvironmentName: 'USNat'
          EnvironmentType: USNat
          ob_release_environment: 'USNat'
          BuildArtifactPattern: ${{ parameters.BuildArtifactPattern }}
          ServiceRootPath: ${{ parameters.ServiceRootPath }}
          RolloutSpecFileName: ${{ parameters.SlotName }}
          Action: 'Staging_${{ parameters.SlotName}}'
    # Deploy to USSec RP
    - ${{ if parameters.DeployToUSSec }}:
      - template: Common/Extension.common.deploy.RP.yml
        parameters:
          ${{ if parameters.DeployToMC }}:
            ${{ if parameters.DeployToFF }}:
              SingleStageDependsOn:
                - 'MC_RP_mc_Staging_${{ parameters.SlotName}}'
                - 'FF_RP_ff_Staging_${{ parameters.SlotName}}'
            ${{ else }}:
              SingleStageDependsOn:
                - 'MC_RP_mc_Staging_${{ parameters.SlotName}}'
          ${{ else }}:
            ${{ if parameters.DeployToFF }}:
              SingleStageDependsOn:
                - 'FF_RP_ff_Staging_${{ parameters.SlotName}}'
            ${{ else }}:
              ${{ if parameters.DeployToProd }}:
                SingleStageDependsOn:
                  - 'Prod_RP_prod_Staging_${{ parameters.SlotName}}'
              ${{ else }}:
                SingleStageDependsOn:
                  - 'Test_set_pipeline_name'
          EnvironmentName: 'USSec'
          EnvironmentType: USSec
          ob_release_environment: 'USSec'
          BuildArtifactPattern: ${{ parameters.BuildArtifactPattern }}
          ServiceRootPath: ${{ parameters.ServiceRootPath }}
          RolloutSpecFileName: ${{ parameters.SlotName }}
          Action: 'Staging_${{ parameters.SlotName}}'